inherit_from:
  - config/rubocop/mruby.yml
  - config/rubocop/standard.yml

AllCops:
  Exclude:
    - bin/**/*
    - config/rubocop/**/*

Lint/EmptyWhen:
  Exclude:
    - "cookbooks/**/*"
    - "roles/**/*"

Style/QuotedSymbols:
  EnforcedStyle: single_quotes
