require:
  - standard
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashSyntax:
  EnforcedShortHandSyntax: never
