git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  sidePanelWidth: 0.15
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
refresher:
  refreshInterval: 3
os:
  editCommand: "nvim"
