execute "brew update"
execute "brew upgrade"

include_role "base"

# osx
package "wget"
package "coreutils"
package "findutils"
package "luajit"
package "lua"
package "git"
package "reattach-to-user-namespace"
# package "z"
# cask
package "dropbox"
package "vlc"
package "virtualbox"
package "vagrant"
package "java"
package "google-drive"
# package "caskroom/cask/android-file-transfer"
# package "caskroom/cask/1password"
# package "caskroom/cask/buttercup"
# package "caskroom/cask/skype"
# package "caskroom/cask/steam"
# package "caskroom/cask/cooviewer"
# package "caskroom/cask/iterm2"
# package "caskroom/cask/dash"
# package "caskroom/cask/android-studio"
