case node[:platform]
when "debian", "ubuntu", "mint"
  package "curl"
  package "tar"
  package "unzip"
  package "jq"
when "redhat", "fedora", "amazon"
  package "curl"
  package "tar"
  package "unzip"
  package "jq"
when "osx", "darwin"
  package "curl"
  package "gnu-tar"
  package "unzip"
  package "jq"
when "arch"
  package "curl"
  package "tar"
  package "unzip"
  package "jq"
when "opensuse"
  package "curl"
  package "tar"
  package "unzip"
  package "jq"
end
