home = node[:home]
user = node[:user]
group_ = node[:group]
config_home = node[:config_home]
repos = node[:repos]
node[:platform]
state_home = node[:state_home]

group group_ do
  user "root"
  action :create
end

mydir "#{home}/.ssh" do
  mode "700"
end

mydir "#{config_home}"
mydir "#{config_home}/git"
mydir "#{config_home}/helix"
mydir "#{config_home}/zsh/z"
mydir "#{config_home}/nvim"
mydir "#{config_home}/spacemacs/layers"
mydir "#{config_home}/Code/User"
mydir "#{config_home}/dictionary"
mydir "#{config_home}/lazygit"
mydir "#{config_home}/fish"
mydir "#{home}/.local"
mydir "#{home}/.local/bin"
mydir "#{home}/.local/themes"
mydir "#{home}/.local/icons"

mydir repos
my_repos = "#{repos}/github.com/dsisnero"
doms_dotfiles = node[:doms_dotfiles]

mydir my_repos

git doms_dotfiles do
  repository "https://github.com/dsisnero/doms_dotfiles"
  action :sync
  only_if { !FileTest.directory? doms_dotfiles }
end

# Create .zshrc.plugin in the config directory
template "#{doms_dotfiles}/config/zsh/.zshrc.plugin" do
  source "templates/.zshrc.plugin.erb"
  owner user
  group group
  mode "644"
end

# include_cookbook "ghq"
# get_repo("dsisnero/doms_dotfiles")

# repos = node[:ghq_root]

# Initialize Fish config with mise setup
template "#{config_home}/fish/config.fish" do
  source "templates/fish/config.fish.erb"
  owner user
  group group
  mode "644"
  only_if "which fish >/dev/null 2>&1" # Only create if Fish is installed
end

# template "#{config_home}/nvim/init.vim" do
#   source "templates/init.vim.erb"
#   owner user
#   group group
# #   not_if "test -e #{config_home}/nvim/init.vim"
# end

template "#{home}/.zlogin" do
  source "templates/.zlogin.erb"
  owner user
  group group
  not_if "test -e #{home}/.zlogin"
end

template "#{home}/.zshrc" do
  source "templates/.zshrc.erb"
  owner user
  group group
end

# Generate wktrees/trunk zsh shell integration file
shell_int_file = "#{doms_dotfiles}/config/zsh/zsh-utils/100_tools/145_wktrees.zsh"
execute "generate wt zsh shell integration" do
  command "wt config shell init zsh > #{shell_int_file}"
  only_if "command -v wt >/dev/null 2>&1"
  not_if "test -f #{shell_int_file}"
end

# Generate wt zsh completions into fpath (mitamae-managed, like atuin)
wt_comp_file = "#{doms_dotfiles}/config/zsh/functions/completions/_wt"
execute "generate wt zsh completions" do
  command "COMPLETE=zsh wt > #{wt_comp_file}"
  only_if "command -v wt >/dev/null 2>&1"
  not_if "test -f #{wt_comp_file}"
end

template "#{home}/.zshenv" do
  source "templates/.zshenv.erb"
  owner user
  group group
end

template "#{home}/.xinitrc" do
  source "templates/.xinitrc.erb"
  owner user
  group group
  not_if "test -e #{home}/.xinitrc"
end

remote_file "#{home}/.tmux.conf" do
  source "files/.tmux.conf"
  owner user
  group group
end

# ssh setting
if node[:is_wsl]
  cmds = [
    "cp -r /mnt/c/.ssh/* #{home}/.ssh/",
    "chown #{user}:#{group} #{home}/.ssh/*",
    "find #{home}/.ssh -type f | xargs chmod 600",
    "find #{home}/.ssh -type d | xargs chmod 700"
  ]

  cmds.each do |cmd|
    user user
    execute cmd do
      only_if "test -d /mnt/c/.ssh"
    end
  end
end

file "#{home}/.ssh/known_hosts" do
  content "# generated by itamae"
  owner user
  group group
  not_if "test -e #{home}/.ssh/known_hosts"
end

# ssh_targets = %w[gitlab.com github.com]
# ssh_targets.each do |target|
#   execute "ssh-keygen -R #{target}" do
#     user user
#   end
#   execute "ssh-keyscan #{target}>>#{home}/.ssh/known_hosts" do
#     user user
#   end
# end

# github_token
if node[:is_wsl]
  cmds = [
    "cp /mnt/c/tools/github_token #{config_home}/git/",
    "chown #{user}:#{group} #{config_home}/git/github_token"
  ]

  cmds.each do |cmd|
    execute cmd do
      only_if "test -e /mnt/c/tools/github_token"
    end
  end
end

dotfile "pip"
dotfile "powerline"
dotfile "broot"
dotfile "helix/external-snippets.toml"
dotfile "helix/config.toml"

# Special handling for snippets directory
# execute "symlink helix snippets" do
#   command "ln -sfT #{doms_dotfiles}/config/helix/snippets #{config_home}/helix/snippets"
#   user user
#   only_if {File.directory?( "#{doms_dotfiles}/config/helix/snippets" }
#   not_if "check_is_symlink (#{config_home}/helix/snippets )"
# end

dotfile "solargraph"
dotfile ".spacemacs"
dotfile ".spacemacs.d"
dotfile "Code/User/settings.json"
dotfile ".ctags"
dotfile "ctags"
# dotfile "nvim/lua"
# dotfile "nvim/nlsp-settings"
dotfile "lazygit/config.yml"
dotfile "yamllint"
dotfile "wezterm"
dotfile ".conkyrc"
dotfile ".textlintrc"
# dotfile '.gemrc' # 追加したいオプションができるまでなし

# mydir "#{home}/.prh-rules/media"
# execute "wget -q https://raw.githubusercontent.com/prh/rules/master/media/WEB%2BDB_PRESS.yml" do
#   user user
#   cwd "#{home}/.prh-rules/media/"
#   not_if "test -e #{home}/.prh-rules/media/WEB+DB_PRESS.yml"
# end

lldb_config_home = File.join(config_home, "lldb")
mydir lldb_config_home

rust_lldb_file = "#{lldb_config_home}/lldb_rust.py"

rust_lldb_source = File.join(node[:doms_dotfiles], "config", "lldb", "lldb_rust.py")

# Install lldb_rust.py script
link rust_lldb_file do
  to rust_lldb_source
  not_if { File.file? rust_lldb_file }
end

node.reverse_merge!(
  rust_lldb_file: rust_lldb_file
)

crystal_lldb_file = File.join(node[:doms_dotfiles], "config", "lldb", "crystal_formatters.py")

helix_language_file = File.join(config_home, "helix", "languages.toml")

# Remove dangling symlink for helix languages.toml if it exists
execute "remove dangling helix languages.toml symlink" do
  command "rm -f #{helix_language_file}"
  only_if "test -L #{helix_language_file}"
  user user
end

helix_log_dir = File.join(state_home, "helix")
helix_log_file = File.join(helix_log_dir, "helix.log")
mydir helix_log_dir

template helix_language_file do
  MItamae.logger.info "in language.toml template creation"
  source "templates/helix/languages.toml.erb"
  owner user
  group group
  mode "644"
  variables(
    rust_import_file: rust_lldb_file,
    crystal_import_file: crystal_lldb_file,
    helix_log_file: helix_log_file
  )
end
