home = node[:home]
user = node[:user]
group_ = node[:group]
config_dir = node[:config_home]
repos = node[:repos]
is_darwin = node[:platform] == 'darwin'

define :mydir, mode: "755" do
  dirpath = params[:name]

  directory dirpath do
    owner user
    group group_
    mode params[:mode]
  end
end

group group_ do
  user 'root'
  action :create
end

mydir "#{home}/.ssh" do
  mode "700"
end

mydir "#{config_dir}"
mydir "#{config_dir}/git"
mydir "#{config_dir}/helix"
mydir "#{config_dir}/zsh/z"
mydir "#{config_dir}/nvim"
mydir "#{config_dir}/spacemacs/layers"
mydir "#{config_dir}/Code/User"
mydir "#{config_dir}/dictionary"
mydir "#{config_dir}/lazygit"
mydir "#{config_dir}/fish"
mydir "#{home}/.local"
mydir "#{home}/.local/bin"
mydir "#{home}/.local/themes"
mydir "#{home}/.local/icons"

mydir repos
my_repos = "#{repos}/github.com/dsisnero"
doms_dotfiles = "#{my_repos}/doms_dotfiles"

mydir my_repos

git doms_dotfiles do
  repository "https://github.com/dsisnero/doms_dotfiles"
  action :sync
  only_if { !FileTest.directory? doms_dotfiles }
end

# include_cookbook "ghq"
# get_repo("dsisnero/doms_dotfiles")

# repos = node[:ghq_root]

# Initialize Fish config with mise setup
template "#{config_dir}/fish/config.fish" do
  source "templates/fish/config.fish.erb"
  owner user
  group group
  mode "644"
  only_if "which fish >/dev/null 2>&1" # Only create if Fish is installed
end

# template "#{config_dir}/nvim/init.vim" do
#   source "templates/init.vim.erb"
#   owner user
#   group group
# #   not_if "test -e #{config_dir}/nvim/init.vim"
# end

template "#{home}/.zlogin" do
  source "templates/.zlogin.erb"
  owner user
  group group
  not_if "test -e #{home}/.zlogin"
end

template "#{home}/.zshrc" do
  source "templates/.zshrc.erb"
  owner user
  group group
  not_if "test -e #{home}/.zshrc"
end

template "#{home}/.zshenv" do
  source "templates/.zshenv.erb"
  owner user
  group group
  not_if "test -e #{home}/.zshenv"
end

template "#{home}/.xinitrc" do
  source "templates/.xinitrc.erb"
  owner user
  group group
  not_if "test -e #{home}/.xinitrc"
end

remote_file "#{home}/.tmux.conf" do
  source "files/.tmux.conf"
  owner user
  group group
end

# ssh setting
if node[:is_wsl]
  cmds = [
    "cp -r /mnt/c/.ssh/* #{home}/.ssh/",
    "chown #{user}:#{group} #{home}/.ssh/*",
    "find #{home}/.ssh -type f | xargs chmod 600",
    "find #{home}/.ssh -type d | xargs chmod 700"
  ]

  cmds.each do |cmd|
    user user
    execute cmd do
      only_if "test -d /mnt/c/.ssh"
    end
  end
end

file "#{home}/.ssh/known_hosts" do
  content "# generated by itamae"
  owner user
  group group
  not_if "test -e #{home}/.ssh/known_hosts"
end

# ssh_targets = %w[gitlab.com github.com]
# ssh_targets.each do |target|
#   execute "ssh-keygen -R #{target}" do
#     user user
#   end
#   execute "ssh-keyscan #{target}>>#{home}/.ssh/known_hosts" do
#     user user
#   end
# end

# github_token
if node[:is_wsl]
  cmds = [
    "cp /mnt/c/tools/github_token #{config_dir}/git/",
    "chown #{user}:#{group} #{config_dir}/git/github_token"
  ]

  cmds.each do |cmd|
    execute cmd do
      only_if "test -e /mnt/c/tools/github_token"
    end
  end
end

dotfile "pip"
dotfile "powerline"
dotfile "broot"
dotfile "helix/external-snippets.toml"
dotfile "helix/languages.toml"
dotfile "helix/config.toml"

# Special handling for snippets directory
# execute "symlink helix snippets" do
#   command "ln -sfT #{doms_dotfiles}/config/helix/snippets #{config_dir}/helix/snippets"
#   user user
#   only_if "test -d #{doms_dotfiles}/config/helix/snippets"
#   not_if "test -L #{config_dir}/helix/snippets"
# end

dotfile "solargraph"
dotfile ".spacemacs"
dotfile ".spacemacs.d"
dotfile "Code/User/settings.json"
dotfile ".ctags"
dotfile "ctags"
# dotfile "nvim/lua"
# dotfile "nvim/nlsp-settings"
dotfile "lazygit/config.yml"
dotfile "yamllint"
dotfile "wezterm"
dotfile ".conkyrc"
dotfile ".textlintrc"
# dotfile '.gemrc' # 追加したいオプションができるまでなし

# mydir "#{home}/.prh-rules/media"
# execute "wget -q https://raw.githubusercontent.com/prh/rules/master/media/WEB%2BDB_PRESS.yml" do
#   user user
#   cwd "#{home}/.prh-rules/media/"
#   not_if "test -e #{home}/.prh-rules/media/WEB+DB_PRESS.yml"
# end
