# theme = "amberwood"
theme = "nord-night"

[editor]
line-number = "relative"
mouse = true
rulers = [80]
bufferline = "multiple"
completion-trigger-len = 1
# Highlight all lines with a cursor
cursorline = true
# auto-pairs = false

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = "|"

[editor.lsp]
auto-signature-help = true
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
character = "╎"
render = true

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"


[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]
