[[sources]] # list of sources to load
name = "friendly-snippets"  # optional name shown on snippet description
git = "https://github.com/rafamadriz/friendly-snippets.git" # git repo with snippets collections

[[sources.paths]] # list of paths to load on current source
scope = ["ruby"]  # optional scopes for current snippets
path = "snippets/ruby/ruby.json"  # where snippet file or dir located in repo
